### ISSUE TITLE
Caused by: java.lang.ArrayIndexOutOfBoundsException: 29

### ISSUE THREAD

**Issue by sdetilly** [nbaztec/coveralls-jacoco-gradle-plugin#20]
Hi, I'm trying to use the plugin to push my code coverage to coveralls, but when I try running `./gradlew jacocoTestReport coverallsJacoco`, I keep getting a weird `task failed > 29`. Here is the stacktrace:
```
* What went wrong:
Execution failed for task 'coverallsJacoco'.
> 29

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task 'coverallsJacoco'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 29
        at org.gradle.plugin.coveralls.jacoco.SourceReportParser.parse(SourceReportParser.kt:88)
        at org.gradle.plugin.coveralls.jacoco.CoverallsReporter.report(CoverallsReporter.kt:43)
        at org.gradle.plugin.coveralls.jacoco.CoverallsJacocoPlugin$apply$1$1.execute(CoverallsJacocoPlugin.kt:20)
        at org.gradle.plugin.coveralls.jacoco.CoverallsJacocoPlugin$apply$1$1.execute(CoverallsJacocoPlugin.kt:13)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:570)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:84)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:555)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:538)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:279)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:268)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:195)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

**Comment by sdetilly** [comment]
It is worth noting that my project uses kotlin multiplatform and I am only testing the common code. Jacoco is already configured correctly and my coveralls block looks like:
```
coverallsJacoco {
    reportPath = "${buildDir}/reports/jacocoTestReport/jacocoTestReport.xml"
    reportSourceSets = files([
            "src/commonMain/kotlin"
    ])
}
```

**Comment by nbaztec** [comment]
Hi, thanks for reporting. Seems like the coverage reported by jacoco and the source file are having a line count mismatch.
Could you perhaps run the task with `--debug` enabled it should give more insight into which file caused the problem. 

Alternatively, if the project is publicly available, I can take a look.

**Comment by sdetilly** [comment]
Unfortunately the project is private. I did the command with --debug and it seems that the file in question has 29 lines (the 29th line is an end of file new line) but the jacocoReport seems to report only 28 lines, like its ignoring the EOF new line. Could that be the problem?

The plugin seems to crash at line `cov.forEach { (line, hits) -> lineHits[line] = hits }` with an `arrayOutOfBounds 29`. So it does look like the plugin sees the new line which might not be present in the coverage file

**Comment by nbaztec** [comment]
Exactly my guess. The line actually comes from `jacocoTestReport.xml` where it's listed. There you should find the file and all the lines reported and perhaps in the report it's using line 29. Could be also a bug with `readlines()` and it'll probably trim the whitespace/newline.

My guess is the latter. Though it's just weird why the report would have a blank line covered.

**Comment by sdetilly** [comment]
I'm wondering if we should safeguard the line `cov.forEach { (line, hits) -> lineHits[line] = hits }` by changing it into:
```
cov.forEach { (line, hits) -> 
   if (line < lineHits.size) {
      lineHits[line] = hits 
   }
}
```
It shouldn't change anything in theory and will prevent weird crashes with EOF lines. What do you think?

**Comment by nbaztec** [comment]
I thought about it as well, and would be a straightforward defensive code block. However, it's still not addressing the real issue (which might even be a bigger bug) that a new-line is never reported in the jacocoReport and the index of `29` states that the report was parsed with a line number of `30` in the jacoco report. This condition should ideally never happen.

Would it be possible to share the jacocoReport itself and/or the `<sourcefile name="MyFile.kt">` block either here or privately for further debugging?

Thanks.

**Comment by sdetilly** [comment]
I'm not sure I can share the whole jacoco report because of the package names and everything, but here is the contents of the class (package name redacted, but all the rest, including empty lines, are the same as in the project:
```kotlin
package foobar.sdk.model.configuration.timetable

import foobar.sdk.model.status.StatusEvent
import kotlinx.serialization.KSerializer
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject

class TimetableDeserializer : KSerializer<TimetableEntity> {
    override fun deserialize(decoder: Decoder): TimetableEntity =
        (decoder as JsonDecoder).let { jsonDecoder ->
            TimetableEntity(jsonDecoder.decodeJsonElement().jsonObject.mapValues {
                jsonDecoder.json.decodeFromJsonElement(ListSerializer(StatusEvent.serializer()), it.value.jsonArray)
            })
        }

    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Timetable", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: TimetableEntity) =
        encoder.encodeSerializableValue(TimetableEntity.serializer(), value)
}

```
It is also worth noting that the coverage tool with codecov is working in this project. I can't be sure why it's working since the parsing happens in their backend though.

**Comment by nbaztec** [comment]
The contents of the file are not that important, rather there should be a section in the `jacocoTestReport.xml` as such:

```xml
  <sourcefile name="MyFile.kt">
            <line nr="23" mi="0" ci="12" mb="0" cb="0"/>
            <line nr="24" mi="0" ci="9" mb="0" cb="0"/>
            <line nr="25" mi="0" ci="8" mb="0" cb="0"/>
            <line nr="26" mi="0" ci="14" mb="0" cb="0"/>
            <line nr="29" mi="0" ci="12" mb="0" cb="0"/>
            <line nr="30" mi="0" ci="3" mb="0" cb="0"/>
            <line nr="31" mi="0" ci="3" mb="0" cb="0"/>
            <line nr="32" mi="0" ci="3" mb="0" cb="0"/>
            <line nr="41" mi="0" ci="41" mb="1" cb="7"/>
            <line nr="42" mi="0" ci="10" mb="0" cb="0"/>
            <line nr="43" mi="0" ci="5" mb="0" cb="0"/>
            <line nr="44" mi="0" ci="6" mb="0" cb="0"/>
            <line nr="45" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="46" mi="0" ci="13" mb="0" cb="4"/>
            <line nr="48" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="49" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="50" mi="0" ci="26" mb="1" cb="3"/>
            <line nr="52" mi="0" ci="12" mb="0" cb="0"/>
            <line nr="53" mi="0" ci="21" mb="0" cb="2"/>
            <line nr="54" mi="0" ci="6" mb="0" cb="0"/>
            <line nr="55" mi="0" ci="12" mb="0" cb="0"/>
            <line nr="66" mi="0" ci="12" mb="1" cb="3"/>
            <line nr="68" mi="0" ci="4" mb="0" cb="0"/>
            <line nr="69" mi="0" ci="17" mb="0" cb="2"/>
            <line nr="71" mi="0" ci="3" mb="0" cb="0"/>
            <line nr="72" mi="0" ci="20" mb="0" cb="0"/>
            <line nr="73" mi="0" ci="7" mb="0" cb="0"/>
            <line nr="76" mi="0" ci="8" mb="0" cb="0"/>
            <line nr="77" mi="1" ci="15" mb="2" cb="2"/>
            <line nr="78" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="79" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="80" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="81" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="82" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="83" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="85" mi="2" ci="2" mb="0" cb="0"/>
            <line nr="96" mi="0" ci="12" mb="0" cb="0"/>
            <line nr="97" mi="0" ci="5" mb="0" cb="0"/>
            <line nr="98" mi="0" ci="7" mb="0" cb="0"/>
            <line nr="99" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="100" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="101" mi="0" ci="10" mb="0" cb="0"/>
            <line nr="102" mi="2" ci="20" mb="2" cb="2"/>
            <line nr="103" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="104" mi="0" ci="4" mb="0" cb="0"/>
            <line nr="105" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="106" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="107" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="108" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="109" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="110" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="112" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="113" mi="12" ci="0" mb="0" cb="0"/>
            <line nr="115" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="124" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="125" mi="0" ci="13" mb="0" cb="2"/>
            <line nr="126" mi="0" ci="3" mb="0" cb="0"/>
            <line nr="128" mi="0" ci="4" mb="0" cb="0"/>
            <line nr="129" mi="0" ci="4" mb="0" cb="0"/>
            <line nr="130" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="137" mi="0" ci="10" mb="0" cb="0"/>
            <line nr="138" mi="0" ci="27" mb="0" cb="2"/>
            <line nr="139" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="149" mi="0" ci="4" mb="0" cb="0"/>
            <line nr="150" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="151" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="152" mi="0" ci="13" mb="0" cb="0"/>
            <line nr="153" mi="0" ci="7" mb="0" cb="0"/>
            <line nr="154" mi="0" ci="13" mb="0" cb="0"/>
            <line nr="155" mi="0" ci="4" mb="0" cb="0"/>
            <line nr="156" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="157" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="159" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="160" mi="0" ci="8" mb="1" cb="1"/>
            <line nr="167" mi="0" ci="5" mb="0" cb="0"/>
            <line nr="168" mi="0" ci="10" mb="0" cb="2"/>
            <line nr="169" mi="0" ci="4" mb="0" cb="0"/>
            <line nr="170" mi="0" ci="4" mb="0" cb="0"/>
            <line nr="171" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="172" mi="0" ci="10" mb="0" cb="4"/>
            <line nr="173" mi="0" ci="2" mb="0" cb="0"/>
            <line nr="174" mi="0" ci="16" mb="0" cb="0"/>
            <line nr="175" mi="0" ci="1" mb="0" cb="0"/>
            <line nr="178" mi="0" ci="15" mb="0" cb="0"/>
            <line nr="179" mi="0" ci="6" mb="0" cb="0"/>
            <line nr="180" mi="0" ci="19" mb="0" cb="6"/>
            <line nr="186" mi="6" ci="9" mb="0" cb="0"/>
            <line nr="188" mi="0" ci="15" mb="0" cb="0"/>
            <counter type="INSTRUCTION" missed="23" covered="743"/>
            <counter type="BRANCH" missed="8" covered="42"/>
            <counter type="LINE" missed="1" covered="87"/>
            <counter type="COMPLEXITY" missed="10" covered="39"/>
            <counter type="METHOD" missed="2" covered="22"/>
            <counter type="CLASS" missed="0" covered="5"/>
        </sourcefile>
```
Would be interesting to look at this blob, especially `<line nr="178" ... />` to figure out more, if it can be provided.

I would anyhow work on perhaps skipping with a warning lines not encountered within the source, though I find it quite strange that this happens at all 😕

**Comment by sdetilly** [comment]
Oh ok. Here is the appropriate part of the jacoco report:
```xml
<sourcefile name="TimetableDeserializer.kt">
    <line nr="15" mi="8" ci="0" mb="0" cb="0"/>
    <line nr="17" mi="12" ci="0" mb="0" cb="0"/>
    <line nr="18" mi="12" ci="0" mb="0" cb="0"/>
    <line nr="19" mi="19" ci="0" mb="0" cb="0"/>
    <line nr="21" mi="1" ci="0" mb="0" cb="0"/>
    <line nr="23" mi="3" ci="0" mb="0" cb="0"/>
    <line nr="24" mi="7" ci="0" mb="0" cb="0"/>
    <line nr="27" mi="7" ci="0" mb="0" cb="0"/>
    <line nr="30" mi="15" ci="0" mb="0" cb="0"/>
    <line nr="31" mi="19" ci="0" mb="0" cb="0"/>
    <line nr="32" mi="10" ci="0" mb="2" cb="0"/>
    <line nr="33" mi="7" ci="0" mb="0" cb="0"/>
    <line nr="35" mi="1" ci="0" mb="0" cb="0"/>
    <counter type="INSTRUCTION" missed="136" covered="0"/>
    <counter type="BRANCH" missed="2" covered="0"/>
    <counter type="LINE" missed="13" covered="0"/>
    <counter type="COMPLEXITY" missed="6" covered="0"/>
    <counter type="METHOD" missed="5" covered="0"/>
    <counter type="CLASS" missed="1" covered="0"/>
</sourcefile>
```
If we don't find the reason for this soon, I would just like you to know that I forked the project to test if my safeguard would show us additional problems. Turns out, the plugin works perfectly with the safeguard :)

**Comment by nbaztec** [comment]
Thanks a lot for provided the appropriate data, it's still super weird these lines:
```xml
   <line nr="30" mi="15" ci="0" mb="0" cb="0"/>
    <line nr="31" mi="19" ci="0" mb="0" cb="0"/>
    <line nr="32" mi="10" ci="0" mb="2" cb="0"/>
    <line nr="33" mi="7" ci="0" mb="0" cb="0"/>
    <line nr="35" mi="1" ci="0" mb="0" cb="0"/>
```

since no such lines exist on source, perhaps the kotlin compiler is inflating the source (it has its nuances with data classes and inline constructs).

Glad to know that the safeguard fixed it for you, I'd release a fix for it over the weekend :) 
If you'd like you can also submit the PR and we can merge it together

**Comment by sdetilly** [comment]
Thank you so much for your time and help! And I agree that the report is super weird. I can't help but wonder why it sees lines that are not present in the source file 🤷

**Comment by nbaztec** [comment]
Thank you for your time as well!

**Comment by nbaztec** [comment]
v1.2.4 is now released with the fix
